name: Deploy Go to Azure Web App
on:
    push:
        branches:
            - main # atau branch yang diinginkan

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.19

            - name: Build Go app
              run: go build -v -o ./bin/main

            - name: Publish to Azure Web App
              uses: azure/webapps-deploy@v2
              with:
                  app-name: stima-gogo
                  # slot-name: <nama-slot> # opsional, jika ingin deploy ke slot
                  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                  package: ./bin/main
